### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by 4JX** [4JX/L5P-Keyboard-RGB#63]
- [ ] Fade but per zone
- [ ] Speed input for effects clamped for stock ones
- [ ] Maybe improve ripple
- [ ] Saving ripple apparently loads as static
  - File does save as ripple*
